apiVersion: v1
kind: Secret
metadata:
  name: ddns-secret
  namespace: prod
data:
  GOOGLE_USER: google-user-base64-encoded
  GOOGLE_PASS: google-password-base64-encoded
  GOOGLE_DOMAIN: google-subdomain-base64-encoded 
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns-google
  namespace: prod
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-curl
            image: curlimages/curl:7.73.0
            args:
            - /bin/sh
            - -c
            - curl -s -u ${GOOGLE_USER}:${GOOGLE_PASS} "https://domains.google.com/nic/update?hostname=${GOOGLE_DOMAIN}"
            envFrom:
            - secretRef:
                name: ddns-secret
          restartPolicy: OnFailure
