# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.
[general]
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=4

[postgresql]
#dsn="postgres://chirpstack_as:chirpstack_ns@postgresql/chirpstack_as?sslmode=disable"
dsn="postgres://chirpstack_as:dbpassword@postgresql/chirpstack_as?sslmode=disable"

[redis]
url="redis://redis:6379"

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"
#server="tcp://localhost:1883"

[application_server.api]
public_host="chirpstack:8001"
#public_host="localhost:8001"


[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="verysecret"
