apiVersion: v1
kind: Secret
metadata:
  name: secret-app-server
  namespace: prod
type: Opaque
stringData:
  chirpstack-application-server.toml: |
    [general]
    log_level=4
    [postgresql]
    dsn="postgres://chirpstack_as:very-secret-password@psql-external-ip/chirpstack_as?sslmode=verify-ca&sslcert=/etc/tls/client-cert.pem&sslkey=/etc/tls/client-key.pem&sslrootcert=/etc/tls/server-ca.pem"
    max_open_connections=1
    max_idle_connections=1
    
    [redis]
    url="redis://redis-service:6379"
    
    [application_server.integration.mqtt]
    server="tcp://mosquitto-service:1883"
    
    [application_server.api]
    public_host="cs-app-service:8001"
    
    [application_server.external_api]
    bind="0.0.0.0:8080"
    jwt_secret="verysecret"

    [application_server.integration]
    enabled=["postgresql"]

    [application_server.integration.postgresql]
    dsn="postgres://chirpstack_as_events:very-secret-password@psql-external-ip/chirpstack_as_events?sslmode=verify-ca&sslcert=/etc/tls/events-as-cert.pem&sslkey=/etc/tls/events-as-key.pem&sslrootcert=/etc/tls/server-ca.pem"
    max_open_connections=1
    max_idle_connections=1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cs-app-server
  name: cs-app-server
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cs-app-server 
  template:
    metadata:
      labels:
        app: cs-app-server
    spec:
      containers:
      - image: chirpstack/chirpstack-application-server:3.13.1
        name: cs-app-server
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /etc/tls && cp /etc/psql-ssl/* /etc/tls/ && chmod -R 400 /etc/tls"]
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8001
          protocol: TCP
        - containerPort: 8003
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/chirpstack-application-server
          name: cs-app-config
        - mountPath: /etc/psql-ssl
          name: psql-ssl
        resources:
          limits:
            memory: "200Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "10m"
      volumes:
      - name: cs-app-config
        secret:
          secretName: secret-app-server
      - name: psql-ssl
        secret:
          secretName: psql-ssl-app-server
---
kind: Service 
apiVersion: v1 
metadata:
  name: cs-app-service
  namespace: prod
spec:
  selector:
    app: cs-app-server
  ports:
    - name: ui
      port: 8080 
      targetPort: 8080
    - name: tst1
      port: 8001 
      targetPort: 8001
    - name: tst2
      port: 8003 
      targetPort: 8003
  type: ClusterIP
